FROM python:3.11-slim
WORKDIR /app
# On copie le requirements qui est à la racine
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# On lance le dashboard qui est dans le dossier DEV
CMD ["streamlit", "run", "DEV/dashboard_map.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]