version: '3.8'

services:
  parkshare-app:
    build:
      context: ..          # On dit à Docker de regarder un niveau au-dessus (la racine Parkshare)
      dockerfile: INFRA/Dockerfile
    container_name: parkshare_container
    ports:
      - "80:8501"          # Port 80 de la VM -> Port 8501 de Streamlit
    volumes:
      - ..:/app            # Synchronise ton code pour les modifs en direct
    restart: always